### ISSUE TITLE
Look there

### ISSUE THREAD

**Issue by Raspifan2020** [geonsey/Free2ViewTV#11]
Hi Geonsey,

this idiot copy m3u´s from many others... they don´t know about this clown!

https://www.vuplus-support.org/wbb4/index.php?thread/143235-astra-19-2e-sat-settings-free-tv-streams/&postID=2092054#post2092054

Before he has copy many m3u´s and entries from Free-IPTV. He has warned him! The he is in the Hall of Shame Nr.3!

https://github.com/Free-IPTV/Countries/blob/master/0001_Stupid_Forking_Hall_of_Shame.txt

Apsattv has him warned also:

https://forums.whirlpool.net.au/thread/9nk6qzy3?p=9#r175 

An now... he copy from you!

**Comment by geonsey** [comment]
He's OK! He actually emailed me for permission to use my work. :-)

**Comment by maggyskins** [comment]
Hi geonsey

I'm sorry that this man "Raspifan2020" is too primitive and knows only insults and internet baiting. I will not lower myself to his level!

**Comment by Raspifan2020** [comment]
> 
> 
> Hi geonsey
> 
> I'm sorry that this man "Raspifan2020" is too primitive and knows only insults and internet baiting. I will not lower myself to his level!

Haha, du hinterhältiger Kerl, du begibst dich ja auf das Niveau der Idioten, die nichts selber gebacken bekommen, deshalb klaust du dir ja alles von anderen Sites zusammen. Du bist eine Schande für die IPTV-Szene und auch für diese VU+ Forum! Es haben mittlerweile mehrere Leute ein Auge auf dein Treiben, die Rechnung... kommt immer hinterher, wenn es zu spät ist! Verarschst täglich die eigenen User im Forum. Erwähnst dasnn FluxusTV, damit hast du dich sowas von lächerlich gemacht! Auf der Website passiert nämlich schon seit langer Zeit NICHTS mehr. Höre einfach auf, die Arbeit anderer zu klauen und die leute im Forum damit zu verarschen. Du bist einfach nur armseelig und kannst nichts selber machen!

**Comment by matthuisman** [comment]
@geonsey
Got your message - thank you and your welcome :)
Maybe consider revoking your permission to this guy. He's now trying to charge $$$ for access to yours and other peoples work.

**Comment by geonsey** [comment]
> @geonsey
> Got your message - thank you and your welcome :)

Thank you for responding, Matt! You have done amazing work and I give you all credit for it when I use it as part of my Free2View TV Project. I did get your original 'unedited' message and, yeah, I regret giving permission to that guy. He seems to be imploding anyways and shutting down his efforts. He blocked me from commenting on his github, but basically I kicked him out of all of my social and revoking any permissions if they come up from this guy. Thanks again for what you do, you are a pioneer in the hobby.

**Comment by geonsey** [comment]
> Hi geonsey
> 
> I'm sorry that this man "Raspifan2020" is too primitive and knows only insults and internet baiting. I will not lower myself to his level!

Yeah, he was not the idiot that he turned out to be when he was copying my work and decided to charge for access to it, claiming the work as part of his own. Definitely is not part of the free streaming community we have all built and respect.

**Comment by matthuisman** [comment]
Yeh. I edited it as I saw your other comments on iptv org and seen you were already well aware what was happening. :)

**Comment by matthuisman** [comment]
Then i remembered its best not to feed trolls. So I won't be responding to him anymore

**Comment by Raspifan2020** [comment]
Anscheinend seid auch ihr 2 einfach nur Vollidioten, die es nicht kapiert haben, was da passiert ist, warum. Mit eurem dummen Verhalten schadet ihr all den Usern! Free-IPTV hat nun dicht gemacht. Viele, sehr viele lesen euren Mist und werden es euch danken!!! Ihr seid eine Schande für AU und NZ!!!!

**Comment by geonsey** [comment]
> Then i remembered its best not to feed trolls. So I won't be responding to him anymore

Agreed. They are done anyways, so it's a moot point, and I know of much better resources that are out there for our free streaming that we know are legit and secure, present company included.

**Comment by geonsey** [comment]
> Anscheinend seid auch ihr 2 einfach nur Vollidioten, die es nicht kapiert haben, was da passiert ist, warum. Mit eurem dummen Verhalten schadet ihr all den Usern! Free-IPTV hat nun dicht gemacht. Viele, sehr viele lesen euren Mist und werden es euch danken!!! Ihr seid eine Schande für AU und NZ!!!!
> Translated: Apparently the two of you are just idiots who didn't get what happened and why. With your stupid behavior you harm all the users! Free-IPTV has now closed. Many, very many read your crap and will thank you for it! You are a shame for AU and NZ !!!!
Don't forget Canada. By the way, all of those "harmed users" know other resources where they can get quality playlists without requiring to pay a fee, because frankly that's what it was. And, furthermore, these resources have been around a lot longer and have been way more reputable that the group was shut down. Personally, I am not sorry: His campaign was not useful or fair to the community that genuinely appreciates Free TV streaming. I wish you and the team (not)Free-IPTV all the best.

And with that, I am locking down this thread. If anyone has any other issues, I welcome the debate in a new thread.
