### ISSUE TITLE
NOOVO - Link not working anymore

### ISSUE THREAD

**Issue by alegag** [geonsey/Free2ViewTV#12]
Hi,

  The "noovo.ca" website has changed in the last week and broken the streaming link in the process.

  Any chance to update that link when the new one that can probably be found here: https://www.noovo.ca/en-direct

Thanks !

**Comment by Sphinxroot** [comment]
yes  i was trying to convert dash to hsl  but my streamlink  hang and close  ... 

if someone wanna try it 

https://pe-ak-lp04a-9c9media.akamaized.net/live/NOOVO/p/dash/20000001/53457a85a91cb498/manifest.mpd

https://pe-ak-lp04a-9c9media.akamaized.net/live/NOOVO/p/dash/20000001/53457a85a91cb498/index/de22f34f/live/stream/h264(608)/v2/192000/init.mp4

https://capi.9c9media.com/destinations/noovo_hub/platforms/desktop/bond/contents/2013891/contentpackages/3864339/manifest.mpd?action=reference
https://capi.9c9media.com/destinations/noovo_hub/platforms/desktop/contents/2013891/contentpackages/3864339?$include=[HasClosedCaptions,breaks,Stacks.ManifestHost.mpd]
https://capi.9c9media.com/destinations/noovo_hub/platforms/desktop/bond/contents/2013891/contentpackages/3864339/manifest.mpd
https://capi.9c9media.com/destinations/noovo_hub/platforms/desktop/contents/2013891/contentpackages/3864339/constraints/blackouts
https://license.9c9media.ca/widevine  <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" value="widevine">

**Comment by geonsey** [comment]
Yes, unfortunately they changed to a dash stream. Now, in most cases, the URL will still work in playlist, so I will test it out while I prepare for an update to the Free2View TV playlist. I will be testing this URL:
https://pe-ak-lp03a-9c9media.akamaized.net/live/NOOVO/p/dash/20000001/53457a85a91cb498/manifest.mpd

**Comment by Sphinxroot** [comment]
#EXTINF:-1,noovo
https://pe-fa-lp03a.9c9media.com/live/NOOVO/p/hls/00000201/716cf4c845225692/manifest.m3u8

in kodi it give only audio

in vlc only video 

need to find the proper one that joint both

**Comment by geonsey** [comment]
> Yes, unfortunately they changed to a dash stream. Now, in most cases, the URL will still work in playlist, so I will test it out while I prepare for an update to the Free2View TV playlist. I will be testing this URL:
> https://pe-ak-lp03a-9c9media.akamaized.net/live/NOOVO/p/dash/20000001/53457a85a91cb498/manifest.mpd

I get a black screen when testing in my players. Apparently it might work in TiviMate, but I have no way to test that. 

This DID work using an HLS browser for Video and Audio
https://pe-fa-lp03a.9c9media.com/live/NOOVO/p/hls/00000201/716cf4c845225692/manifest.m3u8
adding it to my test playlist and checking. Standby.

**Comment by Sphinxroot** [comment]
#EXTINF:-1,noovo video only  720p
https://pe-fa-lp03a.9c9media.com/live/NOOVO/p/hls/00000201/716cf4c845225692/index/de22f34f/live/stream/h264/v1/3500000/manifest.m3u8

#EXTINF:-1,noovo video only 720p
https://pe-fa-lp03a.9c9media.com/live/NOOVO/p/hls/00000201/716cf4c845225692/index/de22f34f/live/stream/h264/v2/3500000/manifest.m3u8

**Comment by Sphinxroot** [comment]
ive found 1 that work in kodi as strm file 

#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
https://pe-ak-lp04a-9c9media.akamaized.net/live/NOOVO/p/dash/00000001/f481c583dbd06b6c/manifest.mpd

**Comment by mikhoul** [comment]
Work also in VLC under Windows so I'm pretty sure it will work on all major players. 

 ![](https://media1.giphy.com/media/DffShiJ47fPqM/giphy.gif)

**Comment by Sphinxroot** [comment]
yeah i need to convert to m3u8  will check that later :)

**Comment by alegag** [comment]
Unfortunatly, it didn't worked for me in Kodi on a ARM system (CoreELEC).

**Comment by mikhoul** [comment]
> yeah i need to convert to m3u8 will check that later :)

No real need to convert it IMO since most new app suport .mpd stream out of the box, Perfect Player and Tivimate both suport MPD stream.

Maybe this tool could help you to do the conversion: https://github.com/squidpickles/mpd-to-m3u8

Regards :octocat:

**Comment by alegag** [comment]
I stand corrected, the sent by Sphinxroot, with the two comments tags, worked for me in Kodi.  Good job man !!!

**Comment by Sphinxroot** [comment]
if you put  in a Noovo.strm  file it work like charm but check proper place to use it

Platform 	Userdata folder path

Android 	Android/data/org.xbmc.kodi/files/.kodi/userdata/ (see note)
https://kodi.wiki/view/Userdata#Android_location

iOS 	        /private/var/mobile/Library/Preferences/Kodi/userdata/

Linux 	        ~/.kodi/userdata/

Mac 	        /Users/<your_user_name>/Library/Application Support/Kodi/userdata/ (see note)
https://kodi.wiki/view/Mac_FAQ#Lion_userdata

OpenELEC 	/storage/.kodi/userdata/

OSMC 	        /home/osmc/.kodi/userdata/

Windows 	%APPDATA%\Kodi\userdata

Windows UWP 	%LOCALAPPDATA%\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\ 



drop the file  then restart kodi 
then go in video  / media source  it will show up :)

**Comment by geonsey** [comment]
Thanks to everybody here for what you are all attempting. If you all find a working m3u8 from all the tools you are using, could you please provide it here? I didn't realize how popular this channel is from my Francophone users of the playlist... :-)

**Comment by alegag** [comment]
@geonsey In the meantime, can the Sphinxroot solution be implemented in the playlist as this seems to work properly ?

```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
https://pe-ak-lp04a-9c9media.akamaized.net/live/NOOVO/p/dash/00000001/f481c583dbd06b6c/manifest.mpd
```

**Comment by geonsey** [comment]
> @geonsey In the meantime, can the Sphinxroot solution be implemented in the playlist as this seems to work properly ?
> 
> ```
> #KODIPROP:inputstreamaddon=inputstream.adaptive
> #KODIPROP:inputstream.adaptive.manifest_type=mpd
> https://pe-ak-lp04a-9c9media.akamaized.net/live/NOOVO/p/dash/00000001/f481c583dbd06b6c/manifest.mpd
> ```

I have no idea on how to do this, so if there are any experts out there who do, I welcome the expertise.

**Comment by mikhoul** [comment]
> In the meantime, can the Sphinxroot solution be implemented in the playlist as this seems to work properly ?

Yes you can, 

If you use Kodi don't forget to ad the 2 lines for the properties and if you use standard M3U8 just use the mpd stream like you would use a m3u8/.ts stream.

Regards :octocat:

**Comment by Sphinxroot** [comment]
actualy the link will work in vlc  or other player that handle mdp file  but for kodi as playlistloader  won`t play that why a .m3u8   is required  and a .m3u8 is universal for all player if someone is good whit streamlink  to pipe out the proper one , people will be happy  .. mine on windlow hang and close and my linux box is dead for now

**Comment by alegag** [comment]
@Sphinxroot it works in Kodi, I'm using it on a CoreELEC, using the two hash-tag you provided, having those in the playlist does the trick.

It does need a recent install of Kodi tho' if I'm not mistaken.  Or have the "inputstream" addon to watch it.  In my case, I had nothing to install, it just worked as soon as I've updated the playlist with the two KODI hash-tags.

**Comment by mikhoul** [comment]
I don't use Kodi but for sure it should work fine since MPD is officially supported in Kodi: https://github.com/mdeguzis/inputstream.mpd

> this addon is part of the official kodi repository and part of each kodi installation

mpd stand for [MPEG-DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) file and is used more and more. From my research most IPTV players support it since 3-4 years.

@Sphinxroot  One question: where have you found the URL "https://pe-ak-lp04a-9c9media.akamaized.net/live/NOOVO/p/dash/00000001/f481c583dbd06b6c/manifest.mpd"   ?   🤔

I searched in the manifest, network request but did not find where the URL is originating.   🤔

**Comment by Sphinxroot** [comment]
> @Sphinxroot it works in Kodi, I'm using it on a CoreELEC, using the two hash-tag you provided, having those in the playlist does the trick.
> 
> It does need a recent install of Kodi tho' if I'm not mistaken. Or have the "inputstream" addon to watch it. In my case, I had nothing to install, it just worked as soon as I've updated the playlist with the two KODI hash-tags.

yes it does but my plugin his a modified  playlisloader addon  that handle a menu that handle  playlist.m3u  in it  and sadly  i cant use MPD stream in it ..  it work m3u8 mp3 mp4 mkv  ,  plugin://plugin. .... my list is hybrid only for kodi

**Comment by Sphinxroot** [comment]
> I don't use Kodi but for sure it should work fine since MPD is officially supported in Kodi: https://github.com/mdeguzis/inputstream.mpd
> 
> > this addon is part of the official kodi repository and part of each kodi installation
> 
> mpd stand for [MPEG-DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) file and is used more and more. From my research most IPTV players support it since 3-4 years.
> 
> @Sphinxroot One question: where have you found the URL "https://pe-ak-lp04a-9c9media.akamaized.net/live/NOOVO/p/dash/00000001/f481c583dbd06b6c/manifest.mpd" ? 
> 
> I searched in the manifest, network request but did not find where the URL is originating.

Some stuff is hided in .js  .json file and i wonder why they used another MPD as main

if you dig in all file arround you will find 


manifest.mpd
manifest.mpd?action=reference
manifest.m3u8
?$include=[HasClosedCaptions,breaks,Stacks.ManifestHost.mpd]
/constraints/blackouts
/destinations/noovo_hub/platforms/desktop/bond/contents/
/destinations/noovo_hub/platforms/desktop/contents


00000001
00000201
0b000201
20000001


https://capi.9c9media.com/
https://ams-ak-lp01-9c9media.akamaized.net/
https://pe-fa-lp03a-9c9media.akamaized.net/
https://pe-fa-lp03a.9c9media.com/
https://pe-fa-lp04a-9c9media.akamaized.net/
https://pe-fa-lp04a.9c9media.com/
https://webapps.9c9media.com/

and so on

**Comment by geonsey** [comment]
Closing issue. Resolved, no available m3u8 stream for this channel.

**Comment by Sphinxroot** [comment]
Kodi Only  if needed  repository.twilight0-1.4.zip repository.twilight0.libs-1.2.zip addon -> plugin.video.streamlink-tester-1.5.4
plugin://plugin.video.streamlink-tester/?action=play&url=https://pe-ak-lp04a-9c9media.akamaized.net/live/NOOVO/p/dash/00000001/f481c583dbd06b6c/manifest.mpd&title=Noovo

**Comment by mikhoul** [comment]
Just for historical purpose for Noovo M3U, this URL `https://pe-fa-lp03a.9c9media.com/live/NOOVO/p/hls/00000201/716cf4c845225692/manifest.m3u8` work in Tivimate and Perfect player (sound and video).

@Sphinxroot  Noovo is tagged "_Audio only_" in your Quebec.m3u
