### ISSUE TITLE
RDI not working anymore

### ISSUE THREAD

**Issue by 2001zig** [geonsey/Free2ViewTV#15]
Hi i think RDI is not working anymore

**Comment by mikhoul** [comment]
I don't know which URL you use but https://rcavlive.akamaized.net/hls/live/704026/canrdi/master.m3u8 is working.

**Comment by 2001zig** [comment]
It doesn’t seem to be the same in free2view list ?

**Comment by mikhoul** [comment]
Just use the link I provided, I monitor Free2View issues here mainly to see if there is new channels that I would be interested in.

Maybe the maintainer will update the RDI link with the one I provided.

Regards :octocat:

**Comment by 2001zig** [comment]
Thanks, let's hope it will be change in the list, 
i'm new in this game and it's seem to be more complicated to integrate one channel in my tivimate app than a list fully fonctionnal.

**Comment by Sphinxroot** [comment]
https://rcavlive.akamaized.net/hls/live/704025/xcanrdi/master_2500.m3u8

**Comment by geonsey** [comment]
This is already in the playlist. Closing the issue.
