### ISSUE TITLE
Adding 

### ISSUE THREAD

**Issue by Sphinxroot** [geonsey/Free2ViewTV#17]
Hi Mr Geonsey  

im offering you ..  if you want .. those list to be added  for your community ..  and they go via your standard of free to view and legal streaming :)

and don`t worry .. i wont charge you 3 euro for them :-x  

https://github.com/Sphinxroot/IPTVM3U/blob/master/Streaming%20Service%20Network/AnthymTV/AnthymTV.m3u
no EPG

https://github.com/Sphinxroot/IPTVM3U/blob/master/Streaming%20Service%20Network/veely.tv/veely.tv.m3u
+ many VOD on site ... EPG Possible via https://veely.tv/tvguide , but i cant see how to scrape it , maybe MR Matt Huisman can give a hand on this , if he have time ,hes doing a lot for the community already :)

https://github.com/Sphinxroot/IPTVM3U/blob/master/Streaming%20Service%20Network/VisionTV/VisionTV.m3u
Mini EPG on site per channel as exemple https://www.visiontv.co.uk/#/channel/ntai on right panel

and keep it up the nice work you do  :)

**Comment by geonsey** [comment]
Hi! Thank you very much! And thank you for including me and allowing me to include your lists into the Free2View TV Project. And, thank you for not forcing me to pay just to look at them ;-)
