### ISSUE TITLE
hi geonsey，i found Freeflix have lots of live channel, can u do sth to grab links?

### ISSUE THREAD

**Issue by isblue01** [geonsey/Free2ViewTV#3]
https://freeflixhq.com/
Hi Geonsey,i came here from ur blog,thx for ur excellent job!i can view all those channel from different content provider  everywhere i go😃😃

**Comment by geonsey** [comment]
Hello. I am afraid I will not be able to extract streams from this app. I only use publicly available streams from originating networks streaming online. -GB
