### ISSUE TITLE
what's the difference between vern-demo and our long used list remote? 

### ISSUE THREAD

**Issue by gfwfuckoff** [geonsey/Free2ViewTV#6]
Hi,GB

**Comment by gfwfuckoff** [comment]
saw ur updates being submitted to these 2 files  randomly before, so i don't know which one i should use to get ur latest  updates instantly😂

**Comment by geonsey** [comment]
Hi. Sorry for the delayed reply, I just noticed this. You should be using the Remote list as this would be the most accurate and stable release. The VERN-DEMO was a "testing" list prior to the stable releases, but it is no longer being used and will be deleted.
