### ISSUE TITLE
KDOC

### ISSUE THREAD

**Issue by jayday23** [geonsey/Free2ViewTV#7]
Could we possible get KDOC on the next update??

Thanks!

https://www.kdoc.tv/live-stream

**Comment by geonsey** [comment]
Hi. Thank you for your request. The KDOC stream was not working when I checked it out, and it appears that it would be broadcasting online only for news broadcasts. So, this would not be an actual TV station feed.

**Comment by jayday23** [comment]
thanks for the follow up! I just realized this as well :) Thanks Again!
